query ShareItem($id: ID!) {
  shareItem(id: $id) {
    id
    date
    item {
      id
      title
      kind
      itemDetails {
        id
        title
        kind
        place
        url
        memo
        priority
      }
    }
  }
}
