name: lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache node_modules PeperomiaWeb
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.OS }}-PeperomiaWeb-${{ hashFiles('**/yarn.lock') }}
        restore-keys:
          ${{ runner.OS }}-PeperomiaWeb-
          ${{ runner.OS }}-
    - name: Install node_modules PeperomiaWeb
      run: yarn --frozen-lockfile
    - name: codegen
      run: yarn codegen
    - name: lint
      run: yarn lint
